---
# tasks file for server
- name: Creates directory /opt/oracle
  file:
    path: /opt/oracle
    state: directory
    mode: 0777

- name: Creates directory /var/www/jenkins
  file:
    path: /var/www/jenkins/1/2/3/4/5/6/7/8/9/0/1/2/3/4/5/6/7/8/9/0
    state: directory
    mode: 0777

- name: Creates directory /var/log/node
  file:
    path: /var/log/node
    state: directory
    mode: 0777

- name: Creates directory /var/www/logs
  file:
    path: /var/www/logs
    state: directory
    mode: 0777
