---
# file: oracle-java/defaults/redhat.yml
#
# Default variables for Redhat-based Linux distributions.
#

oracle_java_dir_source: '/usr/local/src'
oracle_java_download_timeout: 60
oracle_java_rpm_filename: 'jdk-12.0.1_linux-x64_bin.rpm'
oracle_java_home: '/usr/java/default'
oracle_java_rpm_url: 'https://repo.huaweicloud.com/java/jdk/12.0.1+12/jdk-12.0.1_linux-x64_bin.rpm'
oracle_java_rpm_validate_certs: yes
oracle_java_version: 12
oracle_java_version_string: 12.0.1
