---
- name: Register new address
  fortios_address:
    host: "{{ fortinet_firewall_ip }}"
    username: "{{ fortinet_username }}"
    password: "{{ fortinet_password }}"
    state: present
    name: "{{ address_item.address_object[item|int] }}"
    type: ipmask
    value: "{{ address_item.address_object_ip_segment_subnet[item|int] }}"
    comment: "Register {{ address_item.address_object[item|int] }}"
  loop:
  - { address_object: "{{ ip_segment_server.split(',') }}", address_object_ip_segment_subnet: "{{ ip_segment_server_subnet.split(',') }}" }
  loop_control:
    loop_var: address_item
