---
- name: Gather Facts after IOS Upgrade
  ios_facts:

- name: Print Image Version
  debug:
    msg: "The current image verison is {{ ansible_net_version }}"

- name: Set image_version_check to pass/fail
  set_fact:
    image_version_check: "{{ 'pass' if ansible_net_version == desired_image_version else 'fail' }}"

- name: Fail Task if Image Version Check Fails
  fail:
    msg: "Incorrect Version Detected After Upgrade. Please Check!"
  when: image_version_check == 'fail'

- name: Print File System Information
  debug:
    msg: "{{ ansible_net_filesystems_info }}"

- name: Print Line Protocol of Each Interface
  debug:
    msg: "The operation status {{ item.key }} is {{ item.value.operstatus}} and the interface is {{ item.value.lineprotocol }}"
  with_dict: "{{ ansible_net_interfaces }}"

- name: Check for Interfaces that are Not 'Administratively Down' but have Line Protocol that are 'Down'
  fail:
    msg: "Please check Interface {{ item.key }}!"
  when: item.value.operstatus != 'administratively down' and item.value.lineprotocol == 'down '
  with_dict: "{{ ansible_net_interfaces }}"

- name: Perform Post Upgrade Ping Tests to Gateways
  vars:
    ansible_command_timeout: 60
  include: ping_gateway.yml
  loop: "{{ list_of_gateways }}"
