---
- hosts: movile
  vars:
    kea_dhcp_config: true
    kea_dhcp_dhcp4_config:
      Dhcp4:
        renew-timer: 1000
        rebind-timer: 2000
        # Add names of interfaces to listen on
        interfaces-config:
          interfaces:
            - "*"
            # - 'eth0'
            # - 'eth1'
          dhcp-socket-type: raw
        # Use Memfile lease database backend to store leases in a CSV file.
        lease-database:
          type: memfile
          persist: true
          lfc-interval: 0
        # Setup reclamation of the expired leases and leases affinity.
        expired-leases-processing:
          reclaim-timer-wait-time: 10
          flush-reclaimed-timer-wait-time: 25
          hold-reclaimed-time: 3600
          max-reclaim-leases: 100
          max-reclaim-time: 250
          unwarned-reclaim-cycles: 5
        # Global (inherited by all subnets) lease lifetime is mandatory parameter.
        valid-lifetime: 4000
        # Below an example of the simple subnet declarations
        subnet4:
          - subnet: 10.110.16.0/21
            next-server: 10.110.17.0
            pools:
              - pool: "10.110.17.1 - 10.110.17.254"
            reservations:
              - hw-address: "1a:1b:1c:1d:1e:1f"
                ip-address: 10.110.16.0
        option-data:
          - name: domain-name-servers
            data: "10.110.0.245, 10.110.8.245"
          - name: domain-name
            data: "{{ kea_dhcp_pri_domain_name }}"
          - name: boot-file-name
            data: pxelinux.0
        dhcp-ddns:
          enable-updates: false
          qualifying-suffix: "{{ kea_dhcp_pri_domain_name }}"
        # next-server: '0.0.0.0'
        control-socket:
          socket-type: unix
          socket-name: /var/run/kea.socket
      # Logging configuration starts here. It tells Kea servers to store
      # all log messages (on severity INFO or more) in a file.
      # debuglevel variable is used on DEBUG level only.
      Logging:
        loggers:
          - name: kea-dhcp4
            output_options:
              - output: /var/log/kea-dhcp4.log
            severity: INFO
            debuglevel: 0
    pri_domain_name: wavy.systems
  roles:
    - role: ansible-kea-dhcp
  tasks:
