---
- name: Create a vault user
  user:
    name: vault
    password: '$6$F4NWXRFtSdCi8$DsB5vvMJYusQhSbvGXrYDXL6Xj37MUuqFCd4dGXdKd6NyxT3lpdELN07/Kpo7EjjWnm9zusFg/LLFv6oc.ynu/'
    state: present
    shell: /usr/sbin/nologin
    system: no
    createhome: yes
    home: /home/vault

- name: Download and install Vault Server
  unarchive:
    src: https://releases.hashicorp.com/vault/0.11.5/vault_0.11.5_linux_amd64.zip
    dest: /usr/local/bin
    creates: /usr/local/src/vault
    remote_src: yes

- name: Create Vault structure
  file:
    path: /etc/vault
    state: directory

- name: Copy vault QA conf file 
  copy:
    src: config.json
    dest: /etc/vault/config.json
    owner: vault
    group: vault

- name: Copy vault QA start file 
  copy:
    src: vault.service
    dest: /etc/systemd/system/
    owner: root
    group: root

- name: Systemd to reread configs
  systemd: daemon_reload=yes