- name: Create a new virtual machine at vmware by given iso
  hosts: localhost
  tasks:
    - name: Deploy new machine
      vmware_guest:
        hostname: "{{ vcenterIp }}"
        username: "{{ vcenterUser }}"
        password: "{{ vcenterPsswd }}"
        validate_certs: no
        datacenter: "{{ vmDatacenter }}"
        cluster: "{{ vmCluster }}"
        # esxi_hostname: "{{ vmEsxi }}"        
        guest_id: "{{ vmGuestId }}"
        folder: /Ansible/
        # template: "{{ vmTemplate }}"
        name: "{{ vmName }}"
        state: poweredoff
        wait_for_ip_address: no
        annotation: "{{ vmAnnotation }}"
        #cdrom:
        #  type: iso
        #  iso_path: "{{ vmIsoPath }}"
        disk:
        - size_gb: 100
          type: None
          datastore: "{{ vmDiskDatastore }}"
          unit_number: 1
        hardware:
          hotadd_cpu: False
          hotremove_cpu: False
          hotadd_memory: False
          memory_mb: "{{ vmMemory }}"
          num_cpus: "{{ vmCpu }}"
          num_cpu_cores_per_socket: "{{ vmCoresPerSocket }}"
          memory_reservation_lock: False
          mem_limit: "{{ vmMemLimit }}"          
          cpu_limit: "{{ vmCpuLimit }}"
        networks:
          - name: "{{ vmNetworksPortGroup }}"
            vlanId: "{{ vmNetworksVlanId }}"
            device_type: vmxnet3
            start_connected: True
            ip: "{{ vmNetworksIp }}"
            netmask: "{{ vmNetworksNetmask }}"
            gateway: "{{ vmNetworksGateway }}"
        #customization: 
        #  autologon: yes
        #  runonce:
        #  - powershell.exe Rename-Computer -NewName "{{ vmHostname }}" -DomainCredential Domain01\Admin01 -Force
        #  - powershell.exe C:/Apps/WimRm.ps1

               
