---
########################################################
## Esse playbook é responsável por:                     #
## - Configurar a chave publica do usuário ansible para #
## acesso sem necessidade de passar senha               #
##                                                      #
## Autor: wesley.carvalho@t-systems.com.br              #
## Data: fev-2020                                       #
#########################################################
#
- name: Configura chave publica usuário ansible
  hosts: linux 
 
  tasks:
    - name: 'Cria diretorio .ssh se não existir'
      file:
        path: '/home/ansible/.ssh'
        state: directory
        mode: '0755'

    - name: 'Copia chave publica'
      shell:
        cmd: echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDR11nC/D/wzCpSEeBwX/6Q98VqwSGbTrOgn+7fZK/AEliRHDLlF5aN3RcHFeNopbnBLjsFbOfnHMd5oh4sbUUMsaHI5P7+1uThOGOsJ7bwrcQWghhA7tsfS0gAZ9tmd0a+6/r/6QSW1iKTNIweSW1XJYIOb7HE3ZtbNesvNPuXQoa8n7oiUCw2HSjVHY2M390FzgkXrmzEbdhjPsJJMczSiUFJErvKORZK3Cb7JQ6MxzJ8DG7US6zs658f6TqRuAHF9gmKwf94lEjFdKtetgkjTPdhPXvqQxgjMrrv9kNUWvgi7qsMhXRSrhdQlzdC9v2PCX5Hx8bN8ZUm5azBm/VH ansible@sts445lnx" >> /home/ansible/.ssh/authorized_keys
