---
########################################################
# Esse playbook é responsável por:                     #
# - Fazer download dos softwares padrão T-Systems      #
# - Instalar VMware Tools                              #
# - Configurar as interfaces de rede e desabilita IPv6 #
# - Instalação do agente HPSA                          #
# - Configuração do WinAudit                           #
# - Configuração do Event Log                          #
# - Instalação monitoração                             #
# - Desabilita Firewall                                #
# - Instalação MIcrosoft BGInfo                        #
# - Instalação Symantec NetBackup                      #
#                                                      #
# Autor: wesley.carvalho@t-systems.com.br              #
# Data: dez-2019                                       #
########################################################

- name: Install Windows Packages
  hosts: windows 
 
  tasks:
#    - name: 'Download Packages-Windows.zip'
#      win_get_url:
#        url: 'https://xxxxxxxx/Packages-Windows.zip'
#        dest: 'C:\Users\sup3tsys\Downloads\Packages-Windows.zip'
#      ignore_errors: yes

    - name: 'Copy files to windows host'
      win_copy:
        src: '/etc/ansible/packages/Packages-Windows.zip'
        dest: 'C:\Users\sup3tsys\Downloads\Packages-Windows.zip'
      ignore_errors: yes

    - name: 'Unzip Packages-Windows.zip file'
      win_unzip:
        src: 'C:\Users\sup3tsys\Downloads\Packages-Windows.zip'
        dest: 'C:\Users\sup3tsys\Downloads'
      ignore_errors: yes

    - name: 'Install VMware Tools' #VMWare da erro na maquina de teste DAT_ANSIBLE Aqui tem que reiniciar o server
      win_package:
        path: 'C:\Users\sup3tsys\Downloads\Packages-Windows\VMware Tools\setup64.exe'
        product_id: 'VMware-tools-install'
        arguments: '/s /v "/qn reboot=r"'
        state: present
      ignore_errors: yes

    - name: 'Disable IPv6'
      win_command: powershell.exe Disable-NetAdapterBinding -Name * -ComponentID ms_tcpip6 -PassThru
      ignore_errors: yes

#    - name: 'Rename Network Interfaces'
#      win_command: "{{ item }}"
#      with_items:
#        - "{{ customer_network }}"
#        - "{{ customer_adminlan }}"
#        - "{{ customer_backup }}"
#      ignore_errors: yes

    - name: 'Sort Network Interfaces'
      win_command: powershell.exe Get-NetIPInterface | Where-Object {$_.InterfaceAlias -like “Customer”} | Set-NetIPInterface -InterfaceMetric 1
      ignore_errors: yes

    - name: Reboot the machine
      win_reboot:
      ignore_errors: yes

    - name: 'AdminLan network route'
      win_command: cmd.exe /c route add -p 160.118.0.0 mask 255.255.0.0 "{{ gateway_ip }}"
      ignore_errors: yes        

    - name: 'Configure some registries'
      win_command: "{{ item }}"
      with_items:
        - cmd.exe /c reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters" /v DisabledComponents /t REG_DWORD /d 0xff /f
        - cmd.exe /c reg.exe add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128/128" /v Enabled /t REG_DWORD /d 0 /f
        - cmd.exe /c reg.exe add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40/128" /v Enabled /t REG_DWORD /d 0 /f
      ignore_errors: yes

    - name: 'Install HPSA Agent'
      win_command: cmd.exe /c C:\Users\sup3tsys\Downloads\Packages-Windows\HPSA_Agent\opsware-agent-65.0.70477.0-win32-6.0-X64.exe -f --opsw_gw_addr 160.118.133.251:3001 --withmsi --force_full_hw_reg --force_sw_reg
      ignore_errors: yes

    - name: 'Install WinAudit'
      win_shell: install.bat
      args:
        chdir: 'C:\Users\sup3tsys\Downloads\Packages-Windows\WinAudit\'
        executable: cmd
      ignore_errors: yes

    - name: 'Install Retencao de logs (NetBackup)' 
      win_shell: install.bat
      args:
        chdir: 'C:\Users\sup3tsys\Downloads\Packages-Windows\TSBR Retencao_Logs_2016_NetBackup\'
        executable: cmd
      ignore_errors: yes      

#    - name: 'Install Retencao de logs (FTP)' 
#      win_shell: install.bat
#      args:
#        chdir: 'C:\Users\sup3tsys\Downloads\Packages-Windows\TSBR Retencao_Logs_2016_FTP\'
#        executable: cmd
#      ignore_errors: yes

    - name: 'Copy monitoring files to C:\APPS'
      win_copy:
        src: 'C:\Users\sup3tsys\Downloads\Packages-Windows\HP_Operations_Agent'
        dest: 'C:\APPS\'
        remote_src: yes
      ignore_errors: yes

    - name: '1 - Monitoring configuration'
      win_shell: cscript Criar_tsi_oa_activate.conf.vbs "{{ ip_adminlan }}"
      args:
        chdir: 'C:\APPS\HP_Operations_Agent\INSTALL_Wintel'
        executable: cmd
      ignore_errors: yes

    - name: '2 - Monitoring configuration'
      win_shell: Instalar_Agente.bat
      args:
        chdir: 'C:\APPS\HP_Operations_Agent\INSTALL_Wintel'
        executable: cmd
      ignore_errors: yes

    - name: '3 - Monitoring configuration'
      win_shell: Ativar_Monitoracao.bat
      args:
        chdir: 'C:\APPS\HP_Operations_Agent\INSTALL_Wintel'
        executable: cmd
      ignore_errors: yes

    - name: 'Disable Firewall'
      win_firewall:
        state: disabled
        profiles:
        - Domain
        - Private
        - Public
      ignore_errors: yes

    - name: 'Install MIcrosoft BGInfo'
      win_shell: install.bat
      args:
        chdir: 'C:\Users\sup3tsys\Downloads\Packages-Windows\Microsoft BGInfo\'
        executable: cmd
      ignore_errors: yes

    - name: 'Import MIcrosoft BGInfo registry '
      win_regmerge:
        path: 'C:\APPS\BGINFO\bginfo.reg'
      ignore_errors: yes

    - name: 'Run BGINFO configs'
      win_command: cmd.exe /c icacls_bginfo.cmd 
      args:
        chdir: 'C:\Users\sup3tsys\Downloads\Packages-Windows\ICACLS BGINFO\'
      ignore_errors: yes

    - name: 'Install Symantec NetBackup 7.7.3'
      win_shell: silentclient.cmd
      args:
        chdir: 'C:\Users\sup3tsys\Downloads\Packages-Windows\Symantec NetBackup\'
        executable: cmd
      ignore_errors: yes

    - name: 'IP backup route'
      win_command: "{{ item }}"
      with_items:
        - cmd.exe /c route add -p 187.86.221.96 mask 255.255.255.240 198.19.224.3
        - cmd.exe /c route add -p 187.86.220.32 mask 255.255.255.224 198.19.224.3
      ignore_errors: yes

    - name: 'Install SysInternals' 
      win_shell: install.bat
      args:
        chdir: 'C:\Users\sup3tsys\Downloads\Packages-Windows\SysInternals\'
        executable: cmd
      ignore_errors: yes

    - name: 'Install AuditColletService - Admin-LAN'   
      win_shell: install.bat
      args:
        chdir: 'C:\Users\sup3tsys\Downloads\Packages-Windows\T-Systems AuditColletService - Admin-LAN\'
        executable: cmd
      ignore_errors: yes

    - name: 'Rename users'
      win_command: "{{ item }}"
      with_items:
        - cmd.exe /c wmic useraccount where name='Guest' call rename name='tsbruser'
        - cmd.exe /c wmic useraccount where name='Administrator' call rename name='Sup3tsys'
      ignore_errors: yes

#    - name: 'Active Windows'
#      win_command: cmd.exe /c slmgr /ipk "{{ windowsactive }}"
#      ignore_errors: yes

    - name: Reboot the machine
      win_reboot:
      ignore_errors: yes