---
# Refer to https://github.com/ansible/ansible/issues/42200 for more information
# on how to set command_time per task
- name: TFTP New System Image to Boot Flash Memory
  vars:
    ansible_command_timeout: 600
  ios_command:
    commands:
      - command: 'copy tftp://{{ tftp_server_ip }}/{{ new_system_image }} bootflash:'
        prompt: 'Destination filename \[{{ new_system_image }}\]'
        answer: "\r"
    interval: 10
    retries: "{{ number_of_retries | int }}"
    wait_for: result[0] contains OK

- name: Print List of all Files and Directories in bootflash Memory 
  ios_command:
    commands: 'dir bootflash:'

- name: Verify Image File Integrity
  vars:
    ansible_command_timeout: 60
  ios_command:
    commands: 'verify bootflash:/{{ new_system_image }}'
  register: image_verification_results

- name: Set image_integrity_check to pass/fail
  set_fact:
    image_integrity_check: "{{ 'pass' if 'Digital signature successfully verified' in image_verification_results.stdout[0].split('\n')[-1] else 'fail' }}"

- name: Fail Task if Image Integrity Check Fails
  fail:
    msg: "Image Integrity Check Fails. Please check the uploaded image!"
  when: image_integrity_check == 'fail'

- name: Verify MD5 Hash of Image File
  vars:
    ansible_command_timeout: 60
  ios_command:
    commands: 'verify /md5 bootflash:/{{ new_system_image }} {{ md5_hash }}'
  register: md5_hash_verification_results

- name: Set md5_hash_verification to pass/fail
  set_fact:
    md5_hash_verification: "{{ 'pass' if 'Verified' in md5_hash_verification_results.stdout[0].split('\n')[-1] else 'fail' }}"

- name: Fail Task if MD5 Hash Check Fails
  fail:
    msg: "MD5 Hash Check Fails. Please check the uploaded image!"
  when: md5_hash_verification == 'fail'
