---
- hosts: linux
  tasks:
          - name: Create a directory if it does not exist
            file:
                    path: "{{ directory }}"
                    state: directory
                    mode: '0755'

          - name: Create a directory 2
            file:
                    path: "{{ directory_2 }}"
                    state: directory
                    mode: '0755'

