- name: Verificando a existencia de atualizacoes para o sistema
  shell: yum list updates | awk 'f;/Updated Packages/{f=1;}' | awk '{ print $1 }'
  changed_when: updates.stdout_lines | length > 0
  args:
    warn: false
  register: updates

- name: Atualizacoes pendentes
  debug:
    msg: "Encontrado {{ updates.stdout_lines | length }} pacotes para atualizacao:\n\n{{ updates.stdout }}"

- when: updates.stdout_lines | length > 0
  block:
    - name: Instalando atualizacoes via YUM
      yum:
        name: "*"
        state: latest

    - name: Instalando o yum-utils
      package:
        name: yum-utils

    - name: Verificando se precisa de reboot
      shell: needs-restarting -r
      failed_when: false
      register: reboot_required
      changed_when: false

- when: updates.stdout_lines | length > 0 and reboot_required.rc != 0
  block:
    - name: O reboot do servidor se faz necessario para aplicar as atualizacoes
      shell: sleep 3; reboot
      ignore_errors: true
      changed_when: false
      async: 1
      poll: 0

    - name: Aguardando o retorno do servidor apos o reboot
      wait_for_connection:
        timeout: 600
        delay: 20
      register: reboot_result

    - name: Iniciando o reboot
      debug:
        msg: "O servidor reiniciou em {{ reboot_result.elapsed }} segundos."
