---
- name: Install {{ payload }}
  yum:
    name: "{{ payload }}"
    state: latest

- name: Enable {{ payload }} at boot
  service:
    name: "{{ payload }}"
    enabled: yes

- name: Configure haproxy to load balance over OpenStack App servers
  template:
    src: osp_haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  when:  ansible_hostname == "frontend"

- name: Configure haproxy to load balance over Production App servers
  template:
    src: prod_haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  when: ansible_hostname == "frontend1"

- name: Start {{ payload }}
  service:
    name: "{{ payload }}"
    state: restarted
