---
- name: Dump Current State of IOS Device
  vars:
    ansible_command_timeout: 60
  ios_command:
    commands:
      - show ip interface brief
      - show version

- name: Perform Pre-Upgrade Ping Tests to Gateways
  vars:
    ansible_command_timeout: 60
  include: ping_gateway.yml
  loop: "{{ list_of_gateways }}"

- name: Print List of all Files and Directories in bootflash Memory 
  ios_command:
    commands: 'dir bootflash:'

- name: Set File Prompt to Quiet
  ios_config:
    lines: file prompt quiet

- name: Copy startup Configuration file to TFTP Server
  ios_command:
    commands: 'copy start tftp://{{ tftp_server_ip }}/{{ startup_config_backup_file }}'

- name: Copy running Configuration file to TFTP Server
  ios_command:
    commands: 'copy run tftp://{{ tftp_server_ip }}/{{ running_config_backup_file }}'

- name: Disable Silent File Prompt
  ios_config:
    lines: no file prompt quiet

- name: Write Memory
  ios_command:
    commands: 'write memory'
