---
- name: Perform k8s CIS Compliance Check
  hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: /tmp/kubeconfig

  tasks:
    - name: CIS Compliance Scan
      include_role:
        name: k8s_cis
        vars_from: secrets.yml
