---

####################################################################
### Gera dump dos bancos automation_prd e hpooprod                ##
### e os copia para a maquina 1.1.1.1 (/var/backup-mysql-dat) ##
####################################################################

- name: 'Gera dump bancos DAT e copia para uma maquina 1.1.1.1'
  hosts: mysql_tpc

  tasks:

    - name: 'Gerando dump'
      win_command: "{{ item }}"
      with_items:
        - cmd.exe /c mysqldump -h 1.1.1. -u root -p"{{ password }}" automation_prd > E:\Mysql-Dump\automation_prd-{{ansible_date_time.date}}.sql
#        - cmd.exe /c mysqldump -h 1.1.1. -u root -p"{{ password }}" hpooprd > E:\Mysql-Dump\hpooprd-{{ansible_date_time.date}}.sql
#        - cmd.exe /c mysqldump -h 1.1.1. -u root -p"{{ password }}" customer_portal > E:\Mysql-Dump\customer_portal-{{ansible_date_time.date}}-3.sql        

    - name: Listando arquivos a serem copiados
      win_find:
        paths: E:\Mysql-Dump
      register: file_fetch

    - name: 'Copiando arquivos de dump para 1.1.1.1 /var/backup-mysql-dat'
      fetch:
        src: "{{ item.path }}"
        dest: /var/backup-mysql-dat/
        #dest: /tmp/fetch
        flat: yes
      with_items: "{{ file_fetch.files }}"

    - name: Removendo arquivos de backup da 1.1.1.
      win_find:
        paths: E:\Mysql-Dump
      register: file_fetch_remove

    - name: Removendo arquivos de backup da 1.1.1.
      win_file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ file_fetch_remove.files }}"


- name: 'Apagando dados antigos 1.1.1.1 (/var/backup-mysql-dat)'
  hosts: 1.1.1.1
  tasks:

    - command: "{{ item }}"
      with_items:
        - docker cp awx_task:/var/backup-mysql-dat/. /var/backup-mysql-dat/
        - docker exec -it awx_task rm -rf /var/backup-mysql-dat/

    # find all files that are older than six hours
    - find:
        paths: "/var/backup-mysql-dat/"
        age: "21600"
        file_type: file
      register: remove_bkp

    # delete all files that are older than six hours
    - file:
        path: "{{ item.path }}" 
        state: absent
      with_items: "{{ remove_bkp.files }}" 
