---
- name: Update Fortinet Firewall Rule
  fortios_ipv4_policy:
    host: "{{ fortinet_firewall_ip }}"
    username: "{{ fortinet_username }}"
    password: "{{ fortinet_password }}"
    id: "{{ random_id | int }}"
    src_addr: "{{ address_object.src_ip_address[item|int] }}"
    dst_addr: "{{ address_object.dest_ip_address[item|int] }}"
    service: "{{ service_types }}"
    state: "{{ firewall_rule_state }}"
    policy_action: "{{ policy_action }}"
  loop:
  - { src_ip_address: "{{ source_address.split(',') }}", dest_ip_address: "{{ destination_address.split(',') }}" }
  loop_control:
    loop_var: address_object

- name: Update Fortinet Firewall Rule in Reverse Direction
  fortios_ipv4_policy:
    host: "{{ fortinet_firewall_ip }}"
    username: "{{ fortinet_username }}"
    password: "{{ fortinet_password }}"
    id: "{{ random_id }}"
    src_addr: "{{ address_object.dest_ip_address[item|int] }}"
    dst_addr: "{{ address_object.src_ip_address[item|int] }}"
    service: "{{ service_types }}"
    state: "{{ firewall_rule_state }}"
    policy_action: "{{ policy_action }}"
  loop:
  - { src_ip_address: "{{ source_address.split(',') }}", dest_ip_address: "{{ destination_address.split(',') }}" }
  loop_control:
    loop_var: address_object
