---

- name: Create partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present

- name: Create resize a volume group on top of /dev/sdb
  lvg:
    vg: movile
    pvs: /dev/sdb1

- name: Create a logical volume of 100% free with disk /dev/sdb1
  lvol:
    vg: movile
    lv: disk
    size: 100%VG

- name: Create a xfs filesystem on /dev/mapper/movile-disk
  filesystem:
    fstype: xfs
    dev: /dev/mapper/movile-disk
    force: yes


- name: Create directory of movile disk
  file:
    path: /movile
    state: directory
    mode: 0755

- name: Mount up device by movile disk
  mount:
    path: /movile
    src: /dev/mapper/movile-disk
    fstype: xfs
    state: mounted
  register: moviledisk

- name: Change permission after mounted
  file:
    path: /movile
    state: directory
    owner: root
    group: root
    mode: 0755
  when: moviledisk.changed
