---
# tasks file for server
- name: Install EPEL repo
  yum:
     name: "{{ item }}"
     state: latest
  become: yes
  with_items:
     - epel-release

- name: Download YARN repo
  command: wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo
  ignore_errors: yes
  become: yes     

- name: Install common Packages
  yum:
     name: "{{ item }}"
     state: latest
  become: yes
  with_items:
     - htop
     - lsof
     - tcpdump
     - bind
     - bind-utils
     - net-tools
     - mtr 
     - git
     - yum-utils 
     - device-mapper-persistent-data 
     - lvm2
     - wget
     - open-vm-tools
     - ipa-client
     - unzip

- name: Creates directory /opt/oracle
  file:
    path: /opt/oracle
    state: directory
    mode: 0777

- name: Creates directory /var/www/jenkins
  file:
    path: /var/www/jenkins
    state: directory
    mode: 0777

- name: Creates directory /var/log/node
  file:
    path: /var/log/node
    state: directory
    mode: 0777

- name: Creates directory /var/www/logs
  file:
    path: /var/www/logs
    state: directory
    mode: 0777

- name: Download and install Oracle Client
  unarchive:
    src: https://raw.githubusercontent.com/bumpx/oracle-instantclient/master/instantclient-basic-linux.x64-12.2.0.1.0.zip
    dest: /opt/oracle
    creates: /usr/local/src/instantclient
    remote_src: yes

- name: Download NODESOURCE
  command: wget https://rpm.nodesource.com/setup_10.x -O /tmp/setup_10.x
  ignore_errors: yes
  become: yes

- name: Make executable NODESOURCE
  command: chmod +x /tmp/setup_10.x
  ignore_errors: yes
  become: yes

- name: Install NODESOURCE
  command: /tmp/setup_10.x
  ignore_errors: yes
  become: yes

- name: Install nodeJS Packages
  yum:
     name: "{{ item }}"
     state: latest
  become: yes
  with_items:
     - nodejs
     - redis
     - centos-release-scl
     - java-1.8.0-openjdk
     - libaio
     - yarn
     - "@Development Tools"

- name: Install "pm2" package globally.
  npm:
    name: pm2
    global: yes

- name: Generate Oracle-instantclient.conf
  lineinfile:
    dest: /etc/ld.so.conf.d/oracle-instantclient.conf
    line: "/opt/oracle/instantclient_12_2"
    create: yes
    state: present

- name: Run ldconfig
  command: ldconfig
  ignore_errors: no
  become: yes

- name: Change /.bashrc file  - add LD_LIBRARY_PATH
  lineinfile:
    dest: ~/.bashrc
    line: "export LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2:$LD_LIBRARY_PATH"
    state: present

- name: Change /.bashrc file - add NODE_TREND_ENV
  lineinfile:
    dest: ~/.bashrc
    line: "export NODE_TREND_ENV=preprod"
    state: present

- name: Change /.bashrc file - add NODE_ENC_KE
  lineinfile:
    dest: ~/.bashrc
    line: "export NODE_ENC_KEY=OWE3ODM1MDEzNzY0OTA5NjFiMzMxMzcyYjFmOWYwMTE="
    state: present

- name: NPM registry
  command: npm config set registry http://192.168.172.99/nexus/repository/npm-local/
  ignore_errors: no
  become: yes

- name: Ensure redis server is started and enabled to start at boot.
  service: name=redis state=started enabled=yes